### What are Duplicate Records?

Duplicate records are rows in the dataset that repeat the same 
information, either fully or partially. They can happen due to data 
entry mistakes, system errors during data collection, or merging data 
from multiple sources without checking for repeats.

Example: The same customer's record appearing twice in the churn dataset.

In [1]:
import pandas as pd

df = pd.read_csv("customer_churn.csv")
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

print("Total duplicate rows:", df.duplicated().sum())

Total duplicate rows: 40

### Exact Duplicates

Exact duplicates are rows where every single column value matches 
another row completely.

Example: Two identical rows for the same CustomerID, Age, ContractType, 
MonthlyCharges, etc. - with absolutely no difference between them.

In [2]:
exact_duplicates = df[df.duplicated(keep=False)]
print("Number of exact duplicate rows:", len(exact_duplicates))
exact_duplicates.head()

Number of exact duplicate rows: 80

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,PaymentMethod,InternetService,TechSupport,SeniorCitizen,Partner,PaperlessBilling,Churn
33,CUST00034,45.0,Male,9,100.53,2362.30,One Year,Bank Transfer,Fiber Optic,No,1,Yes,Yes,No
348,CUST00349,68.0,M,0,77.22,4005.28,Month-to-Month,Electronic Check,No,Yes,0,Yes,Yes,No
447,CUST00448,39.0,Female,14,85.62,4421.20,Two Year,Electronic Check,Fiber Optic,Yes,0,Yes,No,Yes
796,CUST00797,22.0,M,3,86.72,2556.84,Month-to-Month,Mailed Check,Fiber Optic,No,1,Yes,Yes,No
881,CUST00882,55.0,Female,8,20.75,5093.86,One Year,Credit Card,No,No,0,No,Yes,No

### Partial Duplicates

Partial duplicates are rows that match on some important columns (like 
CustomerID) but differ in others (like MonthlyCharges recorded 
differently due to a billing update).

Example: The same CustomerID appears twice, but with slightly different 
TotalCharges - likely the same customer recorded at two different times.

In [3]:
partial_duplicates = df[df.duplicated(subset=["CustomerID"], keep=False)]
print("Number of rows sharing a duplicate CustomerID:", len(partial_duplicates))
partial_duplicates.sort_values("CustomerID").head(10)

Number of rows sharing a duplicate CustomerID: 80

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,PaymentMethod,InternetService,TechSupport,SeniorCitizen,Partner,PaperlessBilling,Churn
33,CUST00034,45.0,Male,9,100.53,2362.30,One Year,Bank Transfer,Fiber Optic,No,1,Yes,Yes,No
5025,CUST00034,45.0,Male,9,100.53,2362.30,One Year,Bank Transfer,Fiber Optic,No,1,Yes,Yes,No
348,CUST00349,68.0,M,0,77.22,4005.28,Month-to-Month,Electronic Check,No,Yes,0,Yes,Yes,No
5056,CUST00349,68.0,M,0,77.22,4005.28,Month-to-Month,Electronic Check,No,Yes,0,Yes,Yes,No
447,CUST00448,39.0,Female,14,85.62,4421.20,Two Year,Electronic Check,Fiber Optic,Yes,0,Yes,No,Yes
5052,CUST00448,39.0,Female,14,85.62,4421.20,Two Year,Electronic Check,Fiber Optic,Yes,0,Yes,No,Yes
796,CUST00797,22.0,M,3,86.72,2556.84,Month-to-Month,Mailed Check,Fiber Optic,No,1,Yes,Yes,No
5051,CUST00797,22.0,M,3,86.72,2556.84,Month-to-Month,Mailed Check,Fiber Optic,No,1,Yes,Yes,No
881,CUST00882,55.0,Female,8,20.75,5093.86,One Year,Credit Card,No,No,0,No,Yes,No
5023,CUST00882,55.0,Female,8,20.75,5093.86,One Year,Credit Card,No,No,0,No,Yes,No

### Identifying Duplicates - duplicated()

`duplicated()` returns True/False for each row, marking whether it is a 
repeat of an earlier row. By default, it checks all columns, but a 
subset of columns can be given.

In [5]:
print("Full-row duplicates:", df.duplicated().sum())
print("Duplicates based on CustomerID only:", df.duplicated(subset=["CustomerID"]).sum())

Full-row duplicates: 40
Duplicates based on CustomerID only: 40

### Identifying Duplicates - drop_duplicates()

`drop_duplicates()` removes duplicate rows. By default it keeps the 
first occurrence and removes the rest, but this can be changed using the 
`keep` parameter (`"first"`, `"last"`, or `False` to drop all copies).

In [7]:
before = len(df)
df_no_dupes = df.drop_duplicates()
after = len(df_no_dupes)

print("Rows before:", before)
print("Rows after removing exact duplicates:", after)
print("Rows removed:", before - after)

Rows before: 5060
Rows after removing exact duplicates: 5020
Rows removed: 40

### Duplicate Detection Based on Selected Columns

Instead of checking the entire row, we can check specific columns that 
matter most - like CustomerID, since that alone should be unique for 
each customer.

In [8]:
duplicate_customers = df[df.duplicated(subset=["CustomerID"], keep=False)]
print("Rows with duplicate CustomerID:", len(duplicate_customers))
duplicate_customers.sort_values("CustomerID").head(10)

Rows with duplicate CustomerID: 80

,CustomerID,Age,Gender,TenureYears,MonthlyCharges,TotalCharges,ContractType,PaymentMethod,InternetService,TechSupport,SeniorCitizen,Partner,PaperlessBilling,Churn
33,CUST00034,45.0,Male,9,100.53,2362.30,One Year,Bank Transfer,Fiber Optic,No,1,Yes,Yes,No
5025,CUST00034,45.0,Male,9,100.53,2362.30,One Year,Bank Transfer,Fiber Optic,No,1,Yes,Yes,No
348,CUST00349,68.0,M,0,77.22,4005.28,Month-to-Month,Electronic Check,No,Yes,0,Yes,Yes,No
5056,CUST00349,68.0,M,0,77.22,4005.28,Month-to-Month,Electronic Check,No,Yes,0,Yes,Yes,No
447,CUST00448,39.0,Female,14,85.62,4421.20,Two Year,Electronic Check,Fiber Optic,Yes,0,Yes,No,Yes
5052,CUST00448,39.0,Female,14,85.62,4421.20,Two Year,Electronic Check,Fiber Optic,Yes,0,Yes,No,Yes
796,CUST00797,22.0,M,3,86.72,2556.84,Month-to-Month,Mailed Check,Fiber Optic,No,1,Yes,Yes,No
5051,CUST00797,22.0,M,3,86.72,2556.84,Month-to-Month,Mailed Check,Fiber Optic,No,1,Yes,Yes,No
881,CUST00882,55.0,Female,8,20.75,5093.86,One Year,Credit Card,No,No,0,No,Yes,No
5023,CUST00882,55.0,Female,8,20.75,5093.86,One Year,Credit Card,No,No,0,No,Yes,No

### Handling Duplicate Records

Once duplicates are identified, we decide how to handle them:
- Remove exact duplicates completely (safe in most cases).
- For partial duplicates, decide which row to keep (e.g. the most 
  recent one) based on a date or update column.
- Sometimes duplicates are kept if they represent genuinely valid 
  repeated events (not always an error).

# Remove exact duplicates
df_cleaned = df.drop_duplicates()

# For duplicate CustomerID (partial duplicates), keep the last recorded entry
df_cleaned = df_cleaned.drop_duplicates(subset=["CustomerID"], keep="last")

print("Final row count after handling duplicates:", len(df_cleaned))

### Business Rules for Duplicate Removal

Duplicate handling should not be purely mechanical - it should follow 
business logic:
- If CustomerID must be unique, then any repeat is definitely a 
  duplicate to fix.
- If TotalCharges differs between two rows of the same customer, the 
  more recent or more complete record should usually be kept.
- Some "duplicate-looking" rows might actually be valid separate events 
  (e.g. a customer resubscribing after cancelling) - business context 
  decides whether to keep or remove them.

In [10]:
# Example business rule: keep the row with the higher TotalCharges 
# (assumed to be the more complete/updated record) for duplicate CustomerIDs
df_business_rule = df.sort_values("TotalCharges", ascending=False) \
                      .drop_duplicates(subset=["CustomerID"], keep="first")

print("Rows after applying business rule:", len(df_business_rule))

Rows after applying business rule: 5020

### Why Blindly Deleting Duplicates Can Be Dangerous

- Not every repeated-looking row is a mistake - some represent real, 
  separate events (e.g. multiple purchases by the same customer, or a 
  customer resubscribing).
- Deleting rows without checking business context can remove valid data 
  and reduce the dataset's accuracy.
- Removing duplicates based only on a few columns (like CustomerID) 
  might unintentionally erase a legitimate second record, if that 
  business allows customers to have multiple accounts.
- Always understand *why* the duplicate exists before deciding to 
  remove it - not just detect and delete automatically.

In [11]:
# Example: check if "duplicate" CustomerIDs actually have different values elsewhere,
# which could mean they are NOT true duplicates but separate valid records
check = df[df.duplicated(subset=["CustomerID"], keep=False)]
check.sort_values("CustomerID")[["CustomerID", "ContractType", "TotalCharges", "Churn"]].head(10)

     CustomerID    ContractType  TotalCharges Churn
33    CUST00034        One Year       2362.30    No
5025  CUST00034        One Year       2362.30    No
348   CUST00349  Month-to-Month       4005.28    No
5056  CUST00349  Month-to-Month       4005.28    No
447   CUST00448        Two Year       4421.20   Yes
5052  CUST00448        Two Year       4421.20   Yes
796   CUST00797  Month-to-Month       2556.84    No
5051  CUST00797  Month-to-Month       2556.84    No
881   CUST00882        One Year       5093.86    No
5023  CUST00882        One Year       5093.86    No